version: '3.3'
services:
  furya:
    container_name: furya_node
    image: furya/furya:mainnet-alpine
    working_dir: /workspace
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    cap_add:
      - SYS_PTRACE
    env_file:
      - furya.env
    volumes:
      - ./:/workspace
      - ./scripts/setup_genesis.sh:/usr/bin/setup
      - ./scripts/fn.sh:/usr/bin/fn
