version: '3.3'
services:
  furya:
    container_name: furya_node
    image: furya/furya:mainnet-alpine
    working_dir: /workspace
    tty: true
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    cap_add:
      - SYS_PTRACE
    env_file: 
      - furya.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace